### ISSUE TITLE
Web scraper

### ISSUE THREAD

**Issue by watzon** [johnjansen/crystal-libraries-needed#105]
Something like [Wombat](https://github.com/felipecsl/wombat) or [Spidr](https://github.com/postmodern/spidr)

**Comment by HCLarsen** [comment]
This would be useful. I'd do it myself, but I haven't the time.

**Comment by watzon** [comment]
It's a work in progress, but it works https://github.com/watzon/arachnid

**Comment by watzon** [comment]
Arachnid is pretty much finished and fills the need so I'm going to close this
