### ISSUE TITLE
fastimage shard

### ISSUE THREAD

**Issue by alexanderadam** [johnjansen/crystal-libraries-needed#109]
It would be good to have [a fastimage implementation](https://github.com/sdsykes/fastimage).

One of the reasons to have this, is to protect uploads in web frameworks like Kemal, Lucky or Amber from image bombs (like [this gem for Ruby's CarrierWave](https://github.com/DarthSim/carrierwave-bombshelter)).

**Comment by taylorfinnell** [comment]
I made this inspired by fastimage. https://github.com/taylorfinnell/imagecr

It would need to be updated to latest Crystal version, and doesn't support as many image types or have as many features, but maybe it is a start

**Comment by alexanderadam** [comment]
Oh nice, it can even identify images over HTTP(S)! :heart_eyes: 

I guess I can close this then. Thank you for your response!
Maybe we should talk about shards more often. :wink:

**Comment by alexanderadam** [comment]
Now there's also [fastimage.cr](https://github.com/jetrockets/fastimage.cr) from @jetrockets which also works with JPEG and WEBP (apart from having more formats planned) :tada:
