### ISSUE TITLE
XMPP / Jabber client shard

### ISSUE THREAD

**Issue by alexanderadam** [johnjansen/crystal-libraries-needed#110]
It would be nice to have a [XMPP/Jabber :speech_balloon: ](https://xmpp.org/) library like @astro's [xmpp4r](https://github.com/xmpp4r/xmpp4r) or @adhearsion's [blather](https://github.com/adhearsion/blather) (which seems to implement more[?] specifications) or maybe an approach like in other languages, i.e. [xmpp.js](https://github.com/xmppjs/xmpp.js).

I think that XMPP is a nice protocol which became even better since it has support for the encryption extension [OMEMO :tropical_fish:](https://en.wikipedia.org/wiki/OMEMO) (similar to what is used in the [Signal Protocol](https://en.wikipedia.org/wiki/Signal_Protocol)).

Nowadays there are even modern web UIs like [converse.js](https://github.com/conversejs/converse.js/#converse-in-fullpage-mode) and [video conferencing solutions](https://jitsi.org/) so maybe some people / companies decide to spin up a :whale2: Docker container with a XMPP server instead of going for Slack (where [admins could read :mag: private messages](https://mashable.com/2018/03/21/slack-direct-message-privacy-change/) with a 'Corporate Export' and [there's naturally no support for encryption - even if you want it](https://www.nytimes.com/2019/07/01/opinion/slack-chat-hackers-encryption.html)).

Also I always found [XMPP4R easy to use](https://www.sitepoint.com/looking-xmpp-xmpp4r-gem/) although there might be more beautiful DSLs nowadays and [the blather syntax](https://github.com/adhearsion/blather/blob/develop/examples/MUC_echo.rb#L3-L19) is not bad either.

PS: a XMPP server like [vines](https://github.com/negativecode/vines) would be nice as well, but I guess this would mean too much efford

**Comment by naqvis** [comment]
XMPP/Jabber Library for Crystal - https://github.com/naqvis/cr-xmpp

**Comment by alexanderadam** [comment]
@naqvis, I can't emphasise this enough but this is outstanding awesome!
The crystal community can be proud to have you on board.
Thank you so much!

I will close this issue then.
