### ISSUE TITLE
integration with a browser recording library: playwright library / puppeteer library / something similar

### ISSUE THREAD

**Issue by alexanderadam** [johnjansen/crystal-libraries-needed#119]
There's @microsoft's browser automation library called [playwright](https://github.com/microsoft/playwright) which allows to record, generate and replay browser interactions.
There's also a corresponding Python library, called [`playwright-python`](https://github.com/microsoft/playwright-python).

And it's possible to generate Python code with

```bash
$ npx playwright-cli codegen wikipedia.org --target python
```

I guess it would be possible to add another [Code generator](https://github.com/microsoft/playwright-cli/tree/master/src/codegen/languages) for Crystal, too if there'd be something similar to [`playwright-python`](https://github.com/microsoft/playwright-python).

An alternative would be integration with @puppeteer's [`Puppeteer Recorder`](https://github.com/puppeteer/recorder).

It would be great if this could be used with [`lucky_flow`](https://github.com/luckyframework/lucky_flow) later on. So integration with [`selenium.cr`](https://github.com/matthewmcgarvey/selenium.cr) would be useful. Or otherwise integration with something more lightweight / capable doing the CDP protocol, like [`marionette`](https://github.com/watzon/marionette).

**Comment by naqvis** [comment]
Happy to share [Playwright-cr](https://github.com/naqvis/playwright-cr) Crystal version of the Playwright testing and automation library. :laughing:

**Comment by HCLarsen** [comment]
I recently heard about this one:

https://github.com/NeuraLegion/marionette

**Comment by alexanderadam** [comment]
> Happy to share [Playwright-cr](https://github.com/naqvis/playwright-cr) Crystal version of the Playwright testing and automation library. laughing

@naqvis you are absolutely outstanding. Unbelievable! Wow! Thank you so much!

I'm sure this could be useful for @luckyframework and @amberframework, too since it allows recording of actions (i.e. easy reproducting of bugs).

> I recently heard about this one:
> 
> https://github.com/NeuraLegion/marionette

Thank you for this hint. I mentioned marionette in the last sentence of the issue.
My main intention was the recording and replaying issue though. Playwright is pretty much a gold standard in this regards. Now the only missing component is [a matching code generator](https://github.com/microsoft/playwright-cli/tree/master/src/codegen/languages), which doesn't seem too complicated.

I guess I can close this issue then.
Again, thank you so much @naqvis! :pray:

**Comment by watzon** [comment]
> I recently heard about this one:
> 
> https://github.com/NeuraLegion/marionette

That's actually a fork of my project lol

**Comment by alexanderadam** [comment]
> > I recently heard about this one:
> > https://github.com/NeuraLegion/marionette
> 
> That's actually a fork of my project lol

Ah right. I linked it correctly in the first comment, though! :laughing:
