### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by bararchy** [johnjansen/crystal-libraries-needed#25]
ANN
Classifier
LSI 
Etc...

**Comment by marceloboeira** [comment]
@bararchy I am willing to start creating some structures to use ML with Crystal. I will comment here any development.

**Comment by bararchy** [comment]
@marceloboeira Thanks :) 

I started working on basic ANN --> https://github.com/bararchy/crystal-ann 
It was inspired by: https://github.com/gbuesing/neural-net-ruby

**Comment by marceloboeira** [comment]
@bararchy great! I will check how can I contribute 👍

**Comment by bararchy** [comment]
@marceloboeira thanks , that would be awesome , most of it is half working at best , and the Math part is totally out of my league to verify

**Comment by schovi** [comment]
I am trying to port javascript lib https://github.com/cazala/synaptic -> https://github.com/schovi/crystal-synaptic
I choose it because of simple API, pretty examples and overal easy to use feeling.
But it is really far from any output. The JS code is pretty complicated and it took lot of work to untangle it. And bonus is I dont understand to neural networks much :D

**Comment by bararchy** [comment]
Seems there is an active repo here too --> https://github.com/dorkrawk/

**Comment by oltmannsdaniel** [comment]
We really need a new crsyatl Libary index. The awesome-crsyatl stuff hasn't everything in there as I see.

**Comment by Papierkorb** [comment]
@oltmannsdaniel There's been crystalshards.xyz/ for a long time

**Comment by oltmannsdaniel** [comment]
@Papierkorb But we need to split that into different categories like in awesome-crystal

**Comment by RX14** [comment]
@oltmannsdaniel Anything automatic will not be categorised, anything categorised needs someone to categorise it. What do you propose?

**Comment by bew** [comment]
We could use the github topics to categorize? But it won't be good, as peoples can put anything..

**Comment by bararchy** [comment]
Well , the topic is machine learning :) we can use Bayes classifier or KNN algorithm to automatically categorize repos

**Comment by oltmannsdaniel** [comment]
@barachy We talk about general categorization of Crystal Libraries in a huge index.

**Comment by oltmannsdaniel** [comment]
@RX14 We need an huge Index, maybe from the GitHub Crystal account? So everyone will find it.

**Comment by bararchy** [comment]
I got a basic functionality working with FANN bindings in crystal at https://github.com/bararchy/crystal-fann

**Comment by bararchy** [comment]
Well, now that we got FANN and https://github.com/dorkrawk/grey_matter I think that this issue can be closed, at least until a SciCrystal project will happen :)
