### ISSUE TITLE
XML Parser

### ISSUE THREAD

**Issue by MuhammetDilmac** [johnjansen/crystal-libraries-needed#65]
Like a nokogiri :)
http://www.nokogiri.org/

**Comment by konovod** [comment]
There is a https://github.com/kostya/myhtml and https://github.com/madeindjs/Crystagiri
They are not pure crystal though, wrappers around `myhtml` and `libXML` libraries.

**Comment by veelenga** [comment]
There are other choices as well, so it depends on your needs:

* https://github.com/kostya/modest
* https://github.com/maiha/hq.cr
* https://github.com/blocknotes/gumbo-crystal

**Comment by straight-shoota** [comment]
What's wrong with [`XML`](https://crystal-lang.org/api/0.23.1/XML.htm) from standard lib? It's a binding to libxml exactly as nokogiri and I don't see much difference in the wrapper API.

`myhtml` seems like a serious alternative, though the library is still in development.
`hq.cr` and `crystagiri` don't look like they are anywhere near usable for anything.

**Comment by RX14** [comment]
Please use `XML` and suggest any improvements, instead of creating alternatives.
