### ISSUE TITLE
MCrypt

### ISSUE THREAD

**Issue by jwoertink** [johnjansen/crystal-libraries-needed#66]
PHP has [this](http://php.net/manual/en/book.mcrypt.php)
Ruby has [this](https://github.com/kingpong/ruby-mcrypt)
Elixir has [this](https://github.com/system76/elixir-mcrypt)

I have this PHP function that I would like to convert to crystal that requires mcrypt. 

```php
$iv_size = mcrypt_get_iv_size( MCRYPT_BLOWFISH, MCRYPT_MODE_ECB );
$iv = mcrypt_create_iv( $iv_size, MCRYPT_RAND );
$enc = mcrypt_decrypt( MCRYPT_BLOWFISH, $key, $string, MCRYPT_MODE_ECB, $iv );
```

**Comment by straight-shoota** [comment]
I honestly don't see any reason to support a dicontinued crypto library that hasn't been updated in the last 10 years. *You shouldn't use mcrypt anywhere. Ever.*

The blowfish algorithm among others is directly supported by Crystal's standard library.

**Comment by jwoertink** [comment]
Well, that's not an option for me, so I guess I'll have to attempt this, or just not use crystal on this project 🙁

**Comment by Papierkorb** [comment]
@jwoertink Why is not using mcrypt not an option? The algorithms provided by OpenSSL are the same, only their implementations are (supposedly) better.

**Comment by jwoertink** [comment]
Because I don't know anything about cryptography, or any of these algorithms lol. I have to pull data out of a DB that's encrypted with this wonky function in php. My goal was to pull it out and decrypt with crystal with a 1-1 mapping of the function. I would assume I need mcrypt to do that. If you're saying OpenSSL has the same functions, then I guess that means I can use that. I'll give it a shot. thanks.

**Comment by Papierkorb** [comment]
That being said, I wish I could recommend using a libsodium or nacl wrapper over OpenSSL. I can't find an actively maintained one though.

OpenSSLs API makes it easy for you to shoot yourself into your own foot in a cryptographic sense. That won't cause trouble for decryption.

In any case, you should use one of these two libraries over anything else. They're actively maintained, and offer secure and sane defaults. They have bindings for all popular languages too.

**Comment by RX14** [comment]
Well from your PHP code, what you want is to use blowfish cipher in ECB mode, which i'm sure is possible in openssl.
