### ISSUE TITLE
Libsodium or NaCl wrapper, cryptographic libs with sane defaults

### ISSUE THREAD

**Issue by Papierkorb** [johnjansen/crystal-libraries-needed#67]
Apparently, there are right now no wrappers for [Libsodium](https://download.libsodium.org/doc/) or [NaCl](https://nacl.cr.yp.to/).

These are a much better alternative over OpenSSL: Their focus is on sane defaults, and ease of use. Neither of these two can be said about OpenSSL.

Cryptography is hard™. People without academic education within this space (The absolute majority) have it hard, I mean, [even big players mess up](https://medium.freecodecamp.org/why-does-cryptographic-software-fail-often-d660d3cdfdc5).

So let's help those people not creating [the next crypto-messenger fail](https://tobtu.com/decryptocat.php), or [ending up here](http://www.cryptofails.com/).

**Comment by straight-shoota** [comment]
There is at least [andrewhamon/cox](https://github.com/andrewhamon/cox) as a Crystal wrapper for the libsodium box API.

**Comment by didactic-drunk** [comment]
Soon [Awesome Crystal](http://awesomelists.top/#/repos/veelenga/awesome-crystal) will have a Cryptography section with all available shards.

There's a newer fork of cox at [didactic-drunk/cox](https://github.com/didactic-drunk/cox) maintained by me.   An alternative libsodium library is available from [watzon/nacl](https://github.com/watzon/nacl).  The projects may merge if he ever answers my [love letters](https://github.com/watzon/nacl/issues/1).  Or maybe he'll make 5 forks to spite me.  Oh well.

**Comment by didactic-drunk** [comment]
I think this request is satisfied by [didactic-drunk/sodium.cr](https://github.com/didactic-drunk/sodium.cr) and should be closed.

**Comment by konovod** [comment]
I think I should mention there is also [Monocypher](https://monocypher.org/) bindings: https://github.com/konovod/monocypher.cr

**Comment by notramo** [comment]
I think this should be reopened shince @didactic-drunk 's libsodium fork is unmaintained, and they don't seem to be active on GitHub.
