### ISSUE TITLE
Headless Browser

### ISSUE THREAD

**Issue by codenoid** [johnjansen/crystal-libraries-needed#71]
headless (chrome / firefox), or native crystal "headless" (can load ajax request, spa, javascript rendered page, etc), thanks ^^

**Comment by watzon** [comment]
I've started working on this, but it still has a long way to go. https://github.com/watzon/puppet_master

**Comment by straight-shoota** [comment]
Are you porting an existing package?
I see your code downloads a chrome executable and runs that. Why don't you use bindings for WebKit or libchrome?

**Comment by watzon** [comment]
I'm basically porting Chrome's official npm package `Puppeteer` to Crystal. It uses a headless chrome executable and communicates with that.

**Comment by alexanderadam** [comment]
There's also @Ragmaanir's [stoertebeker](https://github.com/Ragmaanir/stoertebeker).
Maybe you could join forces!?

**Comment by RX14** [comment]
There's a selenium shard for crystal, or whatever the spec is these days, is that not the best solution?

**Comment by codenoid** [comment]
i wondering something like python splash (/w non selenium)

**Comment by Ragmaanir** [comment]
@ysbaddaden: Does your selenium shard run a headless browser (I could not really figure it out from the selenium docs)? I only remember selenium as running a browser in the foreground.

**Comment by ysbaddaden** [comment]
It's a webdriver protocol implementation. It will connect to whatever server you've started. Be it selenium or a headless driver.

**Comment by codenoid** [comment]
https://github.com/codenoid/june splash wannabe xD

**Comment by ysbaddaden** [comment]
For example, to run firefox in headless mode with the selenium shard (and selenium server, or maybe geckodriver directly): https://github.com/ysbaddaden/selenium-webdriver-crystal/issues/12#issuecomment-346836930

**Comment by bararchy** [comment]
Can be closed I believe, @ysbaddaden already taken care of it with his shard
