### ISSUE TITLE
Role based authentication library

### ISSUE THREAD

**Issue by tonyvince** [johnjansen/crystal-libraries-needed#77]
A [pundit](https://github.com/elabs/pundit) like multi-role based scalable authentication system would be pretty much helpful

**Comment by ilanusse** [comment]
https://github.com/ilanusse/praetorian

**Comment by ilanusse** [comment]
I'm working on Praetorian, it's a lean Crystal port of Pundit. Feel free to add issues or anything, I'm using it to learn
