### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by bararchy** [johnjansen/crystal-libraries-needed#80]
Binding for BlueZ

**Comment by j8r** [comment]
Can be closed, done in https://github.com/NeuraLegion/blue_cr and https://github.com/crystal-community/bluetooth .
I think one of this project is redundant, @bararchy ?

**Comment by bararchy** [comment]
Can be closed.
One is direct binding to the C lib, the other to the DBUS interface.

**Comment by j8r** [comment]
I don't see any mention of DBUS, it can precised in the `README.md` and the GitHub description.

**Comment by j8r** [comment]
I don't see any mention of DBUS, it can mentioned in the README.md and the GitHub description.
