### ISSUE TITLE
Terminal toolkit like Ruby's HighLine

### ISSUE THREAD

**Issue by lebogan** [johnjansen/crystal-libraries-needed#85]

**Comment by alexanderadam** [comment]
I'm not quite sure whether this would suit your needs but there are many command line shards available.

Just a few examples:

- https://github.com/at-grandpa/clim#clim
- https://github.com/mosop/cli#crystal-cli
- https://github.com/j8r/clicr#clicr
- https://github.com/crystallabs/crysterm#screenshots
- https://github.com/aca-labs/terminimal#terminimal
- https://github.com/maiha/cmds.cr#cmdscr-
- https://github.com/jmakino/clop-crystal#getting-started
- https://github.com/TheMasterCado/easy-cli#usage
- https://github.com/mrrooijen/commander#usage
- https://github.com/jwaldrip/admiral.cr#creating-a-new-cli
- https://github.com/crystal-term/prompt#usage
- https://github.com/crystalrealm/bargs#usage
- https://github.com/picatz/argz#usage
- https://github.com/molovo/crayon#boxes

Is any particular functionality missing?

**Comment by watzon** [comment]
Planning on adding a lot more to crystal-term soon as well

**Comment by alexanderadam** [comment]
Well, I guess feature wise the things that can be found in [crystal-term](https://github.com/crystal-term) should probably make everyone working on CLI apps happy.

That's why I propose to close this issue. What do you think @Sija?

**PS:** Long time no see @watzon! :wink:
