### ISSUE TITLE
Zstandard (zstd) bindings

### ISSUE THREAD

**Issue by Sija** [johnjansen/crystal-libraries-needed#93]
https://github.com/facebook/zstd

**Comment by BlackHabanero** [comment]
[Here](https://github.com/BlackHabanero/zstd-cr) you have it. I don't know if this one is what you will find comfortably useful - but constructive criticism will be appreciated

**Comment by alexanderadam** [comment]
Just FYI: It seems that there's now [a second shard for zstd](https://github.com/didactic-drunk/zstd.cr).

**Comment by BlackHabanero** [comment]
Sure I know about it, author wrote [this](https://github.com/BlackHabanero/zstd-cr/issues/4) to me. Can't decide how to solve this, his code is good in some ways I think, maybe better. I don't know...

**Comment by alexanderadam** [comment]
Ah nice. I missed this bit. :wink: 

I usually like it when projects merge because this means more maintainers and usually more features/less bugs and I also think that having more Crystal than C would be the better approach but performance and reducing GC load doesn't sound bad either. :wink: 

But of course I'm not the one to decide here. Whatever you chose will be alright. :+1: 

Independent from that I think that it's a wonderful thing that you are in a dialogue. :pray:

**Comment by didactic-drunk** [comment]
Second shard maintainer here.  @BlackHabanero and I independently started zstd bindings around
the same time.  My first commit (with working compression/decompression) was around the same time he published his project.  What are the chances?

Unfortunately travel and other [projects](https://github.com/didactic-drunk/sodium.cr) with similar [duplicate effort](https://github.com/watzon/nacl/issues/1) issues delayed my release for 2? months.  I had no idea the other project existed until I went to register the name as @BlackHabanero's didn't exist when I started.  

@BlackHabanero looks new to crystal and I absolutely don't want to discourage his efforts.  At the same time I have a side project that has particular performance requirements and can't sacrifice speed.

**Comment by didactic-drunk** [comment]
To avoid duplicate shards here's a partial list of my future compressor projects:
* brotli 50% of starting in 1-5 months.
* A common compressor interface for swappable compressors 60% chance of starting in 1-5 months.
* snappy and similar 20% chance of starting 1 year.
* lz4 10% chance of starting within 1 year.
* 7zip still researching.

If there is funding the chance of these starting increases proportionally to the amount.

**Comment by alexanderadam** [comment]
> * brotli 50% of starting in 1-5 months.

Be aware that there's also [brotli.cr](https://github.com/naqvis/brotli.cr) from naqvis now.

**Comment by didactic-drunk** [comment]
Thanks @alexanderadam.  The awesome crystal [compression section](https://github.com/veelenga/awesome-crystal#compression) now has everything in one place.
