### ISSUE TITLE
Jupyter Kernel

### ISSUE THREAD

**Issue by LeviZell** [johnjansen/crystal-libraries-needed#95]
I don't know how much is involved to make something similar to the Ruby kernel - iruby (https://github.com/SciRuby/iruby)

It looks like it depends on another package - cztop (https://github.com/paddor/cztop).

**Comment by ihnorton** [comment]
If you don't mind a C++ dependency, https://github.com/QuantStack/xeus can help get a kernel going fairly quickly vs starting from scratch.

(not a Crystal user, at least yet, but happened across this issue and figured the pointer might help)

**Comment by RomainFranceschini** [comment]
[xeus](https://github.com/QuantStack/xeus) would be the easy way but as it's in C++, one would need to write a C wrapper first, and then bind to it from Crystal.

I started to implement the protocol in Crystal, however the [zeromq](https://github.com/crystal-community/zeromq-crystal) shard would need an update first.

**Comment by RomainFranceschini** [comment]
I created a thread on the crystal forum, where I'll post updates of the implementation https://forum.crystal-lang.org/t/jupyter-notebook/2101

**Comment by alexanderadam** [comment]
soooo… this issue can be closed since @RomainFranceschini solved it with [ICrystal](https://github.com/RomainFranceschini/icrystal#icrystal), right?
